name: sen_yone
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-15.0.dev <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^4.0.0
  hive_flutter: ^1.1.0
  flutter_native_splash: ^2.3.2
  google_fonts: 4.0.4


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  latlong2: ^0.8.2
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/imgs/transport1.jpg
    - assets/imgs/DDD.jpg
    - assets/imgs/AFTU.jpg
    - assets/page-1/images/wi-fi.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/vector-wcv.png
    - assets/page-1/images/vector-LCJ.png
    - assets/page-1/images/vector-rrW.png
    - assets/page-1/images/vector-yxE.png
    - assets/page-1/images/vector-tux.png
    - assets/page-1/images/vector-4Ur.png
    - assets/page-1/images/vector-thQ.png
    - assets/page-1/images/auto-group-ecqq.png
    - assets/page-1/images/wi-fi-4Qi.png
    - assets/page-1/images/vector-Fgn.png
    - assets/page-1/images/vector-VZc.png
    - assets/page-1/images/vector-Qkz.png
    - assets/page-1/images/vector-fRL.png
    - assets/page-1/images/vector-C74.png
    - assets/page-1/images/vector-EM8.png
    - assets/page-1/images/vector-6rE.png
    - assets/page-1/images/vector-zpJ.png
    - assets/page-1/images/rectangle-4384-bg.png
    - assets/page-1/images/battery.png
    - assets/page-1/images/rectangle-4384.png
    - assets/page-1/images/vector-bUe.png
    - assets/page-1/images/combined-shape.png
    - assets/page-1/images/vector-96A.png
    - assets/page-1/images/vector-j1k.png
    - assets/page-1/images/vector-N26.png
    - assets/page-1/images/combined-shape-mTY.png
    - assets/page-1/images/vector-cnE.png
    - assets/page-1/images/vector-dmC.png
    - assets/page-1/images/vector-gcz.png
    - assets/page-1/images/wi-fi-od4.png
    - assets/page-1/images/auto-group-ggn6.png
    - assets/page-1/images/auto-group-eq8w.png
    - assets/page-1/images/vector-Ffx.png
    - assets/page-1/images/auto-group-snqa.png
    - assets/page-1/images/vector-tLr.png
    - assets/page-1/images/vector-rPU.png
    - assets/page-1/images/vector-a5p.png
    - assets/page-1/images/vector-uhk.png
    - assets/page-1/images/vector-TjG.png
    - assets/page-1/images/auto-group-wezx.png
    - assets/page-1/images/auto-group-osae.png
    - assets/page-1/images/vector-e8S.png
    - assets/page-1/images/battery-Ppe.png
    - assets/page-1/images/auto-group-rt9q.png
    - assets/page-1/images/auto-group-kd5t.png
    - assets/page-1/images/auto-group-57qn.png
    - assets/page-1/images/vector-dQ6.png
    - assets/page-1/images/auto-group-hyqz.png
    - assets/page-1/images/vector-8bk.png
    - assets/page-1/images/vector-5kN.png
    - assets/page-1/images/vector-Fgn-S74.png
    - assets/page-1/images/vector-fnz.png
    - assets/page-1/images/vector-p5G.png
    - assets/page-1/images/vector-wQn.png
    - assets/page-1/images/vector-Y1p.png
    - assets/page-1/images/vector-RFG.png
    - assets/page-1/images/vector-sKY.png
    - assets/page-1/images/combined-shape-7jg.png
    - assets/page-1/images/battery-K8v.png
    - assets/page-1/images/vector-EMg.png
    - assets/page-1/images/battery-Har.png
    - assets/page-1/images/battery-PcW.png
    - assets/page-1/images/vector-ya2.png
    - assets/page-1/images/wi-fi-VYv.png
    - assets/page-1/images/rectangle-4384-qHC.png
    - assets/page-1/images/vector-434.png
    - assets/page-1/images/vector-wMk.png
    - assets/page-1/images/auto-group-5gkj.png
    - assets/page-1/images/wi-fi-hNA.png
    - assets/page-1/images/vector-Bbp.png
    - assets/page-1/images/vector-WhG.png
    - assets/page-1/images/combined-shape-D1L.png
    - assets/page-1/images/battery-DvS.png
    - assets/page-1/images/vector-NoL.png
    - assets/page-1/images/vector-Uzn.png
    - assets/page-1/images/vector-A6v.png
    - assets/page-1/images/wi-fi-83k.png
    - assets/page-1/images/vector-1za.png
    - assets/page-1/images/vector-68r.png
    - assets/page-1/images/combined-shape-o5C.png
    - assets/page-1/images/vector-k1Q.png
    - assets/page-1/images/vector-sri.png
    - assets/page-1/images/vector-daz.png
    - assets/page-1/images/vector-PKG.png
    - assets/page-1/images/vector-8Jn.png
    - assets/page-1/images/combined-shape-sGN.png
    - assets/page-1/images/vector-2Mx.png
    - assets/page-1/images/vector-Zcn.png
    - assets/page-1/images/vector-QNW.png
    - assets/page-1/images/wi-fi-xev.png
    - assets/page-1/images/vector-pKk.png
    - assets/page-1/images/vector-JE6.png
    - assets/page-1/images/vector-F9L.png
    - assets/page-1/images/vector-cEn.png
    - assets/page-1/images/vector-aBc.png
    - assets/page-1/images/vector-LwU.png
    - assets/page-1/images/vector-XzJ.png
    - assets/page-1/images/vector-bFQ.png
    - assets/page-1/images/battery-REz.png
    - assets/page-1/images/vector-ATU.png
    - assets/page-1/images/auto-group-52zg.png
    - assets/page-1/images/vector-QMg.png
    - assets/page-1/images/vector-vqp.png
    - assets/page-1/images/vector-HJz.png
    - assets/page-1/images/auto-group-ujvg.png
    - assets/page-1/images/vector-t3t.png
    - assets/page-1/images/wi-fi-cVg.png
    - assets/page-1/images/vector-AGJ.png
    - assets/page-1/images/rectangle-4384-jn2.png
    - assets/page-1/images/battery-VHk.png
    - assets/page-1/images/battery-cdG.png
    - assets/page-1/images/combined-shape-TNS.png
    - assets/page-1/images/vector-F3Q.png
    - assets/page-1/images/vector-P9c.png
    - assets/page-1/images/vector-YHQ.png
    - assets/page-1/images/wi-fi-y7p.png
    - assets/page-1/images/combined-shape-unA.png
    - assets/page-1/images/vector-PSS.png
    - assets/page-1/images/vector-kXt.png
    - assets/page-1/images/vector-77Y.png
    - assets/page-1/images/vector-DAa.png
    - assets/page-1/images/auto-group-aqx8.png
    - assets/page-1/images/rectangle-4384-7mk.png
    - assets/page-1/images/combined-shape-3tE.png
    - assets/page-1/images/vector-Jsk.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
